oxideai/mlx-rs

Cargo.toml
mlx-sys/src/lib.rs
src/array.rs
src/device.rs
src/dtype.rs
src/lib.rs

This is an initial implementation of the safe rust wrapper of mlx array. 
Below are some problems found that should probably be discussed (and hopefully resolved)
1. The c api doesn't expose c++ exceptions, which would cause a fatal runtime error 
```sh
fatal runtime error: Rust cannot catch foreign exceptions
```
2. The `Array` type should probably NOT implement the `Clone` trait? Because the c struct mlx_array is atomically reference counted but not protected by `Mutex`
3. A good type alias for `num_complex::Complex<f32>`, `c64` (the current one) or `complex64`. `Complex64` should probably be avoided because `num_complex::Complex64` is actually `num_complex::Complex<f64>`
There is one thing that we probably want to double check after implementing ops
For `mlx_array_data_*` methods, the …

feat(api): add array

---

mlx-sys/build.rs

This PR fixes a bug in the build script that the `Accelerate` framework is not linked when the `accelerate` feature is enabled

Link Accelerate framework

---

examples/tutorial.rs
src/array.rs
src/device.rs
src/lib.rs
src/stream.rs

1. Added `Clone` impl for `Device`, `Stream`, and `StreamOrDevice`
2. Deny `missing_debug_implementations` (pub types that don't have `Debug` impl will give an compile error`)

feat(api): impl Clone and Debug for Device and Stream

---

examples/tutorial.rs
src/array/mod.rs
src/array/operators.rs
src/error.rs
src/fft/fftn.rs
src/fft/mod.rs
src/fft/rfftn.rs
src/ops/arithmetic.rs
src/ops/conversion.rs
src/ops/convolution.rs
src/ops/cumulative.rs
src/ops/factory.rs
src/ops/logical.rs
src/ops/reduction.rs

- add `try_` and `_unchecked` variants for `::item`
- makes `as_slice` take `&mut` and implicitly call `::eval()`

feat(api): eval related updates

---

src/fft/fftn.rs
src/fft/rfftn.rs
src/ops/arithmetic.rs
src/ops/conversion.rs
src/ops/convolution.rs
src/ops/cumulative.rs
src/ops/factory.rs
src/ops/indexing.rs
src/ops/logical.rs
src/ops/reduction.rs
src/ops/shapes.rs
src/stream.rs

This PR changes all functions that take `stream: StreamOrDevice` as arg to use `stream: impl AsRef<Stream>` instead. This would allow user to use both `&stream` and `stream` as argument

Use `stream: impl AsRef<Stream>` instead of `stream: StreamOrDevice` in fn args

---

src/ops/arithmetic.rs
src/ops/convolution.rs
src/ops/factory.rs
src/ops/logical.rs
src/ops/reduction.rs

This PR removes the `stream` param from the Params section in the docs.
The same doc is generated for both `_device` and non`_device` variants, and the latter is likely the most commonly used ones. Having `stream` in the docs for the latter would be confusing

remove stream from param section in docs

---

src/array/macros.rs
src/array/mod.rs
src/macros/array.rs
src/macros/mod.rs

This allows creating array with up to 3 dims using the macro `array!`
```rust
use mlx_rs::array;
// Create a 1D array
let a1 = array![1, 2, 3];
// Create a 2D array
let a2 = array![
[1, 2, 3], 
[4, 5, 6]
];
// Create a 3D array
let a3 = array![
[
[1, 2, 3], 
[4, 5, 6]
], 
[
[7, 8, 9], 
[10, 11, 12]
]
];
```

added traits and macro to help create 1d, 2d, and 3d arrays

---

Cargo.toml
mlx-macros/Cargo.toml
mlx-sys/Cargo.toml

Assign version number for initial release after migrating to the c api.
- `mlx-rs` - 0.14.0 (follows the version of `mlx`)
- `mlx-sys` - 0.0.8 (follows the version of `mlx-c`)
- `mlx-macros` - 0.1.0
I think we can then make a PR to merge `dev` into `main` and make our first release

Set version numbers for 0.14.0 release

---

mlx-rs/examples/tutorial.rs
mlx-rs/src/array/mod.rs
mlx-rs/src/fft/fftn.rs
mlx-rs/src/fft/rfftn.rs
mlx-rs/src/lib.rs
mlx-rs/src/macros/array.rs
mlx-rs/src/macros/internal.rs
mlx-rs/src/ops/arithmetic.rs
mlx-rs/src/ops/conversion.rs
mlx-rs/src/ops/convolution.rs
mlx-rs/src/ops/cumulative.rs
mlx-rs/src/ops/factory.rs
mlx-rs/src/ops/indexing/index_impl.rs
mlx-rs/src/ops/indexing/indexmut_impl.rs
mlx-rs/src/ops/indexing/mod.rs
mlx-rs/src/ops/logical.rs
mlx-rs/src/ops/other.rs
mlx-rs/src/ops/reduction.rs
mlx-rs/src/ops/shapes.rs
mlx-rs/src/random.rs
mlx-rs/src/transforms/compile.rs
mlx-rs/src/transforms/mod.rs
mlx-rs/src/utils.rs

This PR removes all methods that require mutable borrows on `Array`. We might have been too cautious, but it seems like all the computation takes place when `eval` is called, and the `eval` event on the cpp side is protected by mutex and cond var (https://github.com/ml-explore/mlx/blob/969337345ffd34159884c8bf124dbb6eeaa902bb/mlx/backend/no_metal/event.cpp#L21)

Trust synchronization on the cpp side

---

Cargo.toml
mlx-rs/src/fft/fftn.rs
mlx-rs/src/fft/rfftn.rs
mlx-rs/src/ops/conversion.rs
mlx-rs/src/transforms/compile.rs
mlx-sys/Cargo.toml

chore(mlx-c): update to 0.0.9

---

mlx-rs/examples/tutorial.rs
mlx-rs/src/macros/array.rs
mlx-rs/src/ops/conversion.rs

Closes #107 
This PR allows the following usage
```rust
let a = array!([1, 2, 3, 4], shape=[2, 2]);
```

Allow using named `shape` parameter in `array!()` macro

---

.gitmodules
mlx-rs/examples/tutorial.rs
mlx-rs/src/array/operators.rs
mlx-rs/src/error.rs
mlx-rs/src/lib.rs
mlx-rs/src/macros/array.rs
mlx-rs/src/macros/internal.rs
mlx-rs/src/ops/arithmetic.rs
mlx-rs/src/ops/conversion.rs
mlx-rs/src/ops/factory.rs
mlx-rs/src/ops/logical.rs
mlx-rs/src/transforms/compile.rs
mlx-rs/src/transforms/mod.rs
mlx-rs/src/utils.rs
mlx-sys/Cargo.toml
mlx-sys/build.rs
mlx-sys/src/shim/closure.cpp
mlx-sys/src/shim/closure.h
mlx-sys/src/shim/result.cpp
mlx-sys/src/shim/result.h
mlx-sys/src/shim/shim.h

This is probably a better approach than #115 as it doesn't require modification to the upstream c binding.

Use custom c shim for fallible closure

---

mlx-internal-macros/src/generate_builder.rs
mlx-internal-macros/src/lib.rs
mlx-internal-macros/tests/test_generate_builder.rs
mlx-nn/src/activation.rs
mlx-nn/src/losses.rs
mlx-nn/src/optimizers/rmsprop.rs
mlx-nn/src/optimizers/sgd.rs
mlx-rs/src/dtype.rs

I think a derive macro generally implies implementation of a trait of the same name, which is not true in the case of `GenerateBuilder` and `GenerateTestCases`. This PR changes them to function-like proc_macro to avoid such confusion. Functional changes include:
1. The `generate_builder!()` macro now checks if the struct it's applied to derives Default and triggers a panic if it does.

Change `GenarateBuilder` and `GenerateTestCases` to function-like proc_macro

---

mlx-rs/src/ops/indexing/index_impl.rs
mlx-rs/src/ops/indexing/indexmut_impl.rs
mlx-rs/src/ops/indexing/mod.rs

This PR adds support for using `&Array` as index. Other changes include removing the marker trait `IndexBounds` and replaced with impls with explicit types instead of `T: IndexBounds`

Allow indexing with `&Array`

---

examples/mnist/src/main.rs
mlx-internal-macros/src/generate_builder.rs
mlx-internal-macros/src/lib.rs
mlx-nn/src/embedding.rs
mlx-nn/src/optimizers/adagrad.rs
mlx-nn/src/optimizers/mod.rs
mlx-nn/src/optimizers/rmsprop.rs
mlx-nn/src/optimizers/sgd.rs
mlx-rs/src/ops/factory.rs

This PR add implementation of `AdaGrad` optimizer. Other changes include:
1. Added `zeros_like` and `ones_like` factory functions
2. Changed trait function `Optimizer::update` and `Optimizer::update_single` to `Optimizer::apply` and `Optimizer::apply_single`, and these fns now returns `Result<(), Exception>`
3. Added new field attribute argument `#[optional(ty = <Path>)]` to `generate_builder` proc macro

Implement `AdaGrad` optimizer

---

mlx-macros/src/module_parameters.rs
mlx-nn/tests/test_module_parameters.rs
mlx-rs/src/module/module.rs
mlx-rs/src/module/param.rs

`Parameter::is_frozen()`, `ModuleParameters::all_frozen()`, and `ModuleParameters::any_frozen()` now returns `None` if the module contains no trainable parameter

fix: Fix error with checking if parameter is frozen on empty module

---

examples/mnist/src/mlp.rs
mlx-nn/src/activation.rs
mlx-nn/src/container.rs
mlx-nn/src/convolution.rs
mlx-nn/src/dropout.rs
mlx-nn/src/embedding.rs
mlx-nn/src/linear.rs
mlx-nn/src/value_and_grad.rs
mlx-nn/tests/test_module.rs
mlx-rs/src/module/module.rs
mlx-tests/tests/test_optimizers.rs

This change is necessary to implement layers like RNN, which requires two inputs

Add generic type `Args` in `Module` trait to allow binary modules

---

mlx-rs/src/optimizers/adafactor.rs
mlx-rs/src/optimizers/lion.rs
mlx-rs/src/optimizers/sgd.rs

The overhead of using logical ops like `ne`, `gt`, `le`, etc. on scalar arrays is quite high (have seen worst case 100x slower than just creating a new scalar `Array`). This PR removes the unnecessary use of these logical ops in the optimizer impls.

fix: Remove unnecessary logical ops in optimizer

---

mlx-nn/src/value_and_grad.rs
mlx-rs/src/error.rs
mlx-rs/src/transforms/compile.rs
mlx-rs/src/transforms/mod.rs
mlx-rs/src/utils/mod.rs

The default error message yielded from the revamped c binding isn't very helpful (`"mlx_closure returned a non-zero value"`). This PR caches the error caught in the execution of the closure and return that instead.
Fixes: #158

chore: Improve closure error message

---

Cargo.toml
mlx-internal-macros/Cargo.toml
mlx-macros/Cargo.toml
mlx-rs/Cargo.toml
mlx-sys/Cargo.toml

@dcvz Shall we use the workspace version (whatever upstream `mlx` version that `mlx-c` depends on, `"0.21.0"` in this case) for all but `mlx-sys`? And `mlx-sys` will follow the version of `mlx-c` (`"0.1.0"` in this case).

chore: bump and unify version

---

mlx-rs/src/nn/convolution.rs

Closes: #203 
@dcvz This might be a good time to set up a dev branch given that this would be a breaking change?

fix: add dilation and groups field to conv layers

---

mlx-rs/examples/linear_regression.rs
mlx-rs/examples/tutorial.rs
mlx-rs/src/transforms/grad.rs
mlx-rs/src/transforms/value_and_grad.rs

This PR separates `grad` into two functions, one `grad` and the other `grad_with_argnums` where the former uses the default argnums `&[0]` and the latter allows the user to specify the `argnums`. Same is applied to `value_and_grad`

feat: Separate `grad` into two functions

---

Cargo.toml
mlx-rs/src/losses.rs
mlx-rs/src/transforms/mod.rs

Trying to merge this into main because it's a bug fix and not a breaking change. @dcvz WDYT?
See also: https://github.com/ml-explore/mlx-swift/pull/209

fix: Fix wrong condition in smooth l1 loss

---

mlx-rs/src/fft/fftn.rs
mlx-rs/src/fft/mod.rs
mlx-rs/src/fft/rfftn.rs

Removes unnecessary `as_complex64` before calling the corresponding fft C API. This avoids unnecessary evaluation in the fft ops.
Closes #236

refactor: Remove as complex64
